### ISSUE TITLE
integrate create polygon with SAM

### ISSUE THREAD

**Issue by 0ssamaak0** [0ssamaak0/labelmm#22]
e.g., when pressing on create polygon: SAM Toolbar appears and you have the option to create / edit manullay or using SAM

**Comment by Ahmed-Gazzar** [comment]
SAM is now integrated in CREATE MODE with most of its functionalities like (add point, remove point, rectangle, clear, finish)
BUT other functionalities like (replace with SAM) is considered as EDIT MODE
this way is more convenient and logical
