### ISSUE TITLE
Trajectories are not drawn correctly in many senarios

### ISSUE THREAD

**Issue by 0ssamaak0** [0ssamaak0/labelmm#5]
![image](https://user-images.githubusercontent.com/53372259/232424765-073ea75c-2a52-4c23-aedd-c33e47361836.png)

**Comment by Ahmed-Gazzar** [comment]
This is due to id switch
we integrated some tracking algorithms which are quit good
check StrongSORT and it will be much better
NOTE: you can edit the labels when id switch happens (we can NOT prevent them ALL at the end) and the trajectories will be updated automatically
